//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager_parts_0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Митниця
    {
        public int code { get; set; }
        public Nullable<System.DateTime> Дата_реєстрації { get; set; }
        public Nullable<int> Код_товару { get; set; }
        public Nullable<int> Код_працівника { get; set; }
        public Nullable<int> Відцоток_додаткової_вартості { get; set; }
        public Nullable<int> Кількість { get; set; }
        public Nullable<System.DateTime> Строк_зберігання_СТЗ { get; set; }
        public Nullable<int> Номер_рахунку { get; set; }
        public string Cтатус { get; set; }
    
        public virtual Поставки_товарів Поставки_товарів { get; set; }
        public virtual Працівники Працівники { get; set; }
    }
}
