//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager_parts_0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки_товарів
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставки_товарів()
        {
            this.Митниця = new HashSet<Митниця>();
        }
    
        public int code { get; set; }
        public Nullable<System.DateTime> Час_поставки_товару { get; set; }
        public Nullable<int> код_Постачальника { get; set; }
        public Nullable<int> код_Товару { get; set; }
        public Nullable<int> Код_працівника { get; set; }
        public Nullable<int> Кількість { get; set; }
        public string Назва_компанії_перевізника { get; set; }
        public string Статус_митниці { get; set; }
    
        public virtual Контер_агенти Контер_агенти { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Митниця> Митниця { get; set; }
        public virtual Найменування_товарів Найменування_товарів { get; set; }
        public virtual Працівники Працівники { get; set; }
    }
}
