//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager_parts_0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Працівники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Працівники()
        {
            this.Митниця = new HashSet<Митниця>();
            this.Поставки_товарів = new HashSet<Поставки_товарів>();
            this.Продаж_товарів = new HashSet<Продаж_товарів>();
        }
    
        public int code { get; set; }
        public string ИПБ { get; set; }
        public Nullable<System.DateTime> Дата_працевлаштування { get; set; }
        public string Посада { get; set; }
        public Nullable<int> Зарплата { get; set; }
        public string Примітка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Митниця> Митниця { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки_товарів> Поставки_товарів { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продаж_товарів> Продаж_товарів { get; set; }
    }
}
